name: Test List Job ID

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Explore-GH-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          sleep 10s
          echo "Hi Mom"

      - name: Upload Artifact
        run: echo hello > world.txt
      - uses: actions/upload-artifact@v4
        with:
          path: world.txt
          name: my-artifact
